### ISSUE TITLE
Making this pip installable

### ISSUE THREAD

**Issue by maple3142** [josephsurin/lattice-based-cryptanalysis#1]
I think it would be good if it is possible to install this using `pip install .`

A minimal working example would be like this:

`pyproject.toml`:

```toml
[project]
name = "lbc_toolkit"
version = "0.0.1"
dependencies = [
    "sagemath-standard >= 9.8",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
```

`setup.cfg`:

```cfg
[options]
include_package_data = True

[options.package_data]
lbc_toolkit = **/*.sage
```

I am not sure `"sagemath-standard >= 9.8"` dependency requirement will work correctly in all setups, but it works correctly for me.
